interface CloudflareEnv {
  DB: D1Database;
  ASSETS: Fetcher;
  NEXT_PUBLIC_STORAGE_BRAIN_API_KEY: string;
  NEXT_PUBLIC_STORAGE_BRAIN_URL: string;
  NEXT_PUBLIC_STORAGE_BRAIN_WORKSPACE_ID?: string;
  GOOGLE_CLOUD_VISION_API_KEY: string;
}
